runtime: nodejs20

handlers:
  # Serve static assets from the dist folder
  - url: /assets
    static_dir: dist/assets

  # Serve images
  - url: /images
    static_dir: dist/images

  # Serve fonts
  - url: /fonts
    static_dir: dist/fonts

  # Serve favicon
  - url: /favicon.ico
    static_files: dist/favicon.ico
    upload: dist/favicon.ico

  # Serve the SPA for all other routes
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
